Add RA/Dec Plot
ZwickyTransientFacility/scope pull request #25
Opened 2021-05-05 20:25 UTC by mcoughlin

![radec__cepheid](https://user-images.githubusercontent.com/2291947/117204563-11d8b500-adb6-11eb-8d67-7e3fba1fb236.png)

Possible plot for the sky location.

2021-05-05 20:31 UTC, AshishMahabal commented
The plot looks great. Can we add some RA/Dec labels?

2021-05-05 20:38 UTC, dmitryduev requested changes
Looks great, just a couple comments:
- You need to configure the pre-commit hook to ignore fits files (see https://github.com/ZwickyTransientFacility/scope/blob/main/.pre-commit-config.yaml).
- Change alpha on the plotted positions, otherwise things can get too crowded.
- I would shade out the part of the sky that is not visible from Palomar, otherwise the plots with our golden sets will be confusing.

2021-05-05 20:38 UTC, dmitryduev commented on scope/utils.py
> +    alpha = 1.0
I'd do 0.75 or something.

2021-05-05 21:40 UTC, mcoughlin commented
![radec__cepheid](https://user-images.githubusercontent.com/2291947/117212874-831d6580-adc0-11eb-96e3-5fe920d1aff6.png)

@AshishMahabal @dmitryduev

2021-05-06 01:52 UTC, dmitryduev commented
Looks really nice, thanks @mcoughlin! Linting failed for whatever reason, but otherwise should be ready for merging. As said, I just want to wait until EDR3 is ingested into G (should be a couple days - I realized that I am also ingesting AllWISE and PS1 to be able to run x-match when ingesting features).

2021-05-06 01:52 UTC, dmitryduev approved these changes

2021-05-10 17:54 UTC, janvanroestel commented on scope/utils.py
> +
we should add an optiion to change the symbol size to avoid overlap of symbols; either if the sample is large or very clustered.

2021-05-10 17:54 UTC, janvanroestel commented on scope/utils.py
> +        plt.savefig(save)
Looks very good overall

2021-05-11 00:46 UTC, dmitryduev commented
Got a verbal 👍🏻 from @janvanroestel, so merging.

2021-05-11 00:46 UTC, merged